[global]
type=global
endpoint_identifier_order=username,ip,anonymous
user_agent=SecureSIP-Engine

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0:8088

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5062

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5062

; ----- alice -----
[alice-auth]
type=auth
auth_type=userpass
username=alice
password=${ALICE_PASS}

[alice]
type=aor
max_contacts=2
remove_existing=yes
support_path=yes

[alice]
type=endpoint
context=internal
disallow=all
allow=ulaw
allow=alaw
allow=g722
allow=opus
auth=alice-auth
aors=alice
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
webrtc=yes
support_path=yes
from_domain=151-115-164-7.sslip.io
media_address=151.115.164.7
dtls_verify=fingerprint
dtls_cert_file=/etc/asterisk/certs/fullchain.pem
dtls_private_key=/etc/asterisk/certs/privkey.pem
dtls_setup=actpass
ice_support=yes
media_use_received_transport=yes

; ----- bob -----
[bob-auth]
type=auth
auth_type=userpass
username=bob
password=${BOB_PASS}

[bob]
type=aor
max_contacts=2
remove_existing=yes
support_path=yes

[bob]
type=endpoint
context=internal
disallow=all
allow=ulaw
allow=alaw
allow=g722
allow=opus
auth=bob-auth
aors=bob
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
webrtc=yes
support_path=yes
from_domain=151-115-164-7.sslip.io
media_address=151.115.164.7
dtls_verify=fingerprint
dtls_cert_file=/etc/asterisk/certs/fullchain.pem
dtls_private_key=/etc/asterisk/certs/privkey.pem
dtls_setup=actpass
ice_support=yes
media_use_received_transport=yes
