[kamailio]
enabled  = true
filter   = kamailio
logpath  = /var/log/kamailio/kamailio.log
port     = 5060,5061,8443
protocol = udp,tcp
action   = iptables-allports[name=kamailio, protocol=all]
bantime  = 3600
findtime = 60
maxretry = 3
